`once-common-structs` and `once-connection-type`
Wulf/dsync pull request #80
Opened 2023-09-11 12:58 UTC by hasezoey

This PR adds options `once-common-structs` and `once-connection-type`

These options are currently NOT the default

to make them default, should they still be a option or should it be unconfigurable? also i dont think `no-once-connection-type` or `no-once-common-structs` sounds good, any suggestions?

re #56

2023-09-29 19:17 UTC, Wulf requested changes
Awesome -- yeah, this should definitely be the default and it's a great refactor of the generated output. We can make it the default in another PR

Let's do this for the tests:
Add a second table to the schema and also remove all fields from the tables except maybe an ID, similar to my comment for #82

2023-09-30 18:28 UTC, hasezoey commented
added a second table and rebased onto main

2023-10-07 19:54 UTC, Wulf approved these changes
It would be nice to add another test for these options + the single-model-file option but if we're thinking of making these the default, it should be okay to ship this!

Again, thanks for this great refactor of the generated code

2023-10-07 19:54 UTC, Wulf commented on src/lib.rs
> +        }
this is a great catch, thank you

2023-10-08 12:49 UTC, hasezoey commented
> It would be nice to add another test for these options + the single-model-file option

added with 007ace83c139f67e1d85ed4829cf0b6953d121df (all options together), i didnt have a better name for the folder though

2023-10-08 17:41 UTC, Wulf approved these changes
awesome, thank you @hasezoey

2023-10-09 11:43 UTC, merged